---
title: "drug_plate_2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plater)
library(formattable)
library(dplyr)
library(zoo)
library(htmlTable)
library(reshape2)
library(mtpview1)
library(stringr)
library(scales)
library(cowplot)
```


```{r load data}
##load data proccessed

sD<-read.csv("d4-SD.csv")

MD<-read.csv("d4_MD.csv")

## merge PD with Plate Map

data_sum1 <- add_plate(
  data = sD, 
  file = "PLATE MAP.csv",
  well_ids_column = "well")

data_meas1 <- add_plate(
  data = MD, 
  file = "PLATE MAP.csv",
  well_ids_column = "well")

##split dataframe based on plate 
y<-split(data_sum1, data_sum1$plate, drop = F)
yy<-split(data_meas1, data_meas1$plate, drop = F)

```

```{r ds, include=FALSE}


S6.14y<-y$S1L1
S6.45y<-y$S1L2
s6.113y<-y$S2L1
U5.05y<-y$S2L2
W.34.70y<-y$S3L1
WLP644y<-y$S3L2


U5.05my<-yy$S2L2%>%
  arrange(runtime)
S6.14my<-yy$S1L1%>%
  arrange(runtime)
S6.45my<-yy$S1L2%>%
  arrange(runtime)
S6.113my<-yy$S2L1%>%
  arrange(runtime)
W.34.70my<-yy$S3L1%>%
  arrange(runtime)
WLP644my<-yy$S3L2%>%
  arrange(runtime)
```

```{r auc }

U5auc<-calc_AUC_plate(U5.05my)
S14auc<-calc_AUC_plate(S6.14my)
S45auc<-calc_AUC_plate(S6.45my)
S113auc<-calc_AUC_plate(S6.113my)
W34auc<-calc_AUC_plate(W.34.70my)
Wlpauc<-calc_AUC_plate(WLP644my)

```

```{r relative fit}

U5rel<-relative_fitness(lll, U5auc, "U5-05", BYauc)
S14rel<-relative_fitness(lll,S14auc, "S6-14", BYauc)
S45rel<-relative_fitness(lll, S45auc, "S6-45", BYauc)
S113rel<-relative_fitness(lll, S113auc, "S6-113", BYauc)
W34rel<-relative_fitness(lll, W34auc, "W-34/70", BYauc)
Wlprel<-relative_fitness(lll, Wlpauc, "WLP-644", BYauc)

samples_relative<-rbind(U5rel,S14rel,S45rel,S113rel,W34rel,Wlprel)

```

```{r doubling time and percent inhibition}

U5dtpi<-doubling_inhibtion(U5.05y,lll, "U5-05")
S14dtpi<-doubling_inhibtion(S6.14y,lll, "S6-14")
S45dtpi<-doubling_inhibtion(S6.45y,lll, "S6-45")
S113dtpi<-doubling_inhibtion(s6.113y,lll, "S6-113")
W34dtpi<-doubling_inhibtion(W.34.70y,lll, "W-34/70")
Wlpdtpi<-doubling_inhibtion(WLP644y,lll, "WLP-644")

sample_dt_pi<-rbind(U5dtpi, S14dtpi, S45dtpi, S113dtpi, W34dtpi, Wlpdtpi)
```

```{r summary metrics}
d4_sum_metrics<-merge(samples_relative, sample_dt_pi)
```

```{r averages}


average_sample_stats4 <- aggregate(list(AVE_A=d4_sum_metrics$A, 
                                       AVE_mu=d4_sum_metrics$mu, 
                                       AVE_lambda=d4_sum_metrics$lambda,
                                       AVE_DT=d4_sum_metrics$DT, 
                                       AVE_auc= d4_sum_metrics$auc, 
                                       ave_rel_inhib_off_Plate = d4_sum_metrics$percent_inhib_off_plate,
                                       ave_rel_inhib = d4_sum_metrics$percent_inhib_onplate,
                                       ave_rel_fit = d4_sum_metrics$rel_fit_on_plate,
                                       ave_rel_fit_off_plate=d4_sum_metrics$rel_fit_off_plate, 
                                       ave_rel_fit_to_by = d4_sum_metrics$rel_fit_to_by), 
                           by = list(compound=d4_sum_metrics$sample, plate= d4_sum_metrics$plate), mean)%>%
  distinct()
```

```{r plots}
library(viridis)
plate<- c("S1L1", "S1L2", "S2L1","S2L2","S3L1","S3L2")
strain<-c("S6.14","S6.45", "S6.113", "U5.05","W.34.70","WLP.644")

ps4<-as.data.frame(cbind(plate,strain))

d4_sum_measures<-merge(d4_sum_metrics, data_meas1)%>%
  merge(ps4)

write.csv(d4_sum_metrics, "C:/Users/SamBr/documents/yeast/RF2/d4_sum_mets.csv" )
write.csv(average_sample_stats4, "C:/Users/SamBr/documents/yeast/RF2/d4_ave_sum_mets.csv")



d4_sum_measures%>% 
    unnest() %>% 
    mtp_ggplot(aes(plate = plate, well = well)) + 
    mtp_spec_96well() + 
    geom_footprint() + 
    geom_notched_border() +
    geom_col_label() + 
    geom_row_label() + 
    geom_well_rect(aes(fill = rel_fit_on_plate)) + 
    geom_well_line(aes(x = runtime, y = measure)) + 
    geom_well_text(aes(label = sample))+
  scale_fill_viridis(option = "A") +
    facet_wrap(~plate, ncol = 1)



```


```{r mean a sd}