---
title: "drug  plate"
author: "Sam"
date: "August 20, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
getwd()
library(tidyverse)
library(plater)
library(formattable)
library(dplyr)
library(zoo)
library(htmlTable)
library(reshape2)
library(mtpview1)
library(stringr)
library(scales)
```

load proccessed data
- merege with plate meta data

load meassure data
```{r rename by postion}

rename_col_by_position <- function(df, position, new_name) {
  new_name <- enquo(new_name)
  new_name <- quo_name(new_name)
  select(df, !! new_name := !! quo(names(df)[[position]]), everything())
}
```

split list into dataframe based on strain 
```{r doublingtime and inhib}

doubling_time<- function(x){
  
  dt<-x%>%
    mutate(DT = log(2)/mu/3600)
}

#x=summary stats
percent_inhib_onplate <-function(x){
  
   rel_scores<-dcast(x, well~plate, fun.aggregate = mean, value.var = "mu")%>%
    column_to_rownames(var="well")
 
  
  on_rel<-x%>% 
    group_by(solvent) %>% 
    bind_rows(., .) %>%
    mutate(percent_inhib_onplate = ifelse(test = (solvent == 'ETOH'), 
                                      yes = (((rel_scores["C01", 1]-mu)/rel_scores["C01", 1])*100),
                                      no = ifelse(test = (solvent == 'ETOH-2'), 
                                                  yes = (((rel_scores["C07", 1]-mu)/rel_scores["C07", 1])*100),
                                                  no = ifelse(test = (solvent == 'DMSO'),
                                                              yes = (((rel_scores["B01", 1]-mu)/rel_scores["B01", 1])*100),
                                                              no = ifelse(test = (solvent =='DMSO-2'),
                                                                          yes = (((rel_scores["B07", 1]-mu)/rel_scores["B07", 1])*100),
                                                                          no = ifelse(test = (solvent =='H2O'),
                                                                                      yes= (((rel_scores["A01", 1]-mu)/rel_scores["A01", 1])*100),
                                                                                      no =  (((rel_scores["A07", 1]-mu)/rel_scores["A07", 1])*100)))))))%>%
    
    unique()
}

## off plate 
#x= table off plate ave summary measures
#y= table sample summary measures
#z = current sample name in ""
off_plate_perecnt_inhibition <- function( y, x, z){
  
  rel_scores<-dcast(x, compound~sample, fun.aggregate = mean, value.var = "AVE_mu")%>%
    column_to_rownames(var="compound")
  
  off_rel<-y%>% 
    group_by(solvent) %>% 
    bind_rows(., .) %>%
    mutate(percent_inhib_off_plate = ifelse(test = (solvent == 'ETOH'), 
                                      yes = (((rel_scores["ETOH", z]-mu)/rel_scores["ETOH", z])*100),
                                      no = ifelse(test = (solvent == 'ETOH-2'), 
                                                  yes = (((rel_scores["ETOH", z]-mu)/rel_scores["ETOH", z])*100),
                                                  no = ifelse(test = (solvent == 'DMSO'),
                                                              yes = (((rel_scores["DMSO", z]-mu)/rel_scores["DMSO", z])*100),
                                                              no = ifelse(test = (solvent =='DMSO-2'),
                                                                          yes = (((rel_scores["DMSO", z]-mu)/rel_scores["DMSO", z])*100),
                                                                          no = ifelse(test = (solvent =='H2O'),
                                                                                      yes= (((rel_scores["H2O", z]-mu)/rel_scores["H2O", z])*100),
                                                                                      no =  (((rel_scores["H2O", z]-mu)/rel_scores["H2O", z])*100)))))))%>%
    
    unique()
  }

#x= table off plate ave summary measures
#y= table sample summary measures
#z = current sample name in ""

doubling_inhibtion<-function(y,x,z){
  y%>%
  off_plate_perecnt_inhibition(x,z)%>%
  percent_inhib_onplate()%>%
  doubling_time()
}
```

Function: calculate Area Under the Curve -- add as new column 
```{r AUC}
calc_AUC <- function(n,z){
  x <- n %>%
    filter(well == z)%>%
    select(runtime)  
  
  X<-x$runtime
  
  
  y <- n %>%
    filter(well == z)%>%
    select(measures_pp) 
  Y<-y$measures_pp 
  
  
  sum(diff(X)*rollmean(Y,2))
}


calc_AUC_plate <- function(BY4743m){
  
  A01<- calc_AUC(BY4743m,"A01") 
  B01<- calc_AUC(BY4743m,"B01") 
  C01<- calc_AUC(BY4743m,"C01") 
  D01<- calc_AUC(BY4743m,"D01") 
  E01<- calc_AUC(BY4743m,"E01") 
  F01<- calc_AUC(BY4743m,"F01") 
  G01<- calc_AUC(BY4743m,"G01")  
  H01<- calc_AUC(BY4743m,"H01")  
  
  A02<- calc_AUC(BY4743m,"A02") 
  B02<- calc_AUC(BY4743m,"B02") 
  C02<- calc_AUC(BY4743m,"C02")  
  D02<- calc_AUC(BY4743m,"D02") 
  E02<- calc_AUC(BY4743m,"E02") 
  F02<- calc_AUC(BY4743m,"F02") 
  G02<- calc_AUC(BY4743m,"G02") 
  H02<- calc_AUC(BY4743m,"H02") 
  
  A03<- calc_AUC(BY4743m,"A03") 
  B03<- calc_AUC(BY4743m,"B03") 
  C03<- calc_AUC(BY4743m,"C03") 
  D03<- calc_AUC(BY4743m,"D03") 
  E03<- calc_AUC(BY4743m,"E03") 
  F03<- calc_AUC(BY4743m,"F03") 
  G03<- calc_AUC(BY4743m,"G03") 
  H03<- calc_AUC(BY4743m,"H03") 
  
  A04<- calc_AUC(BY4743m,"A04") 
  B04<- calc_AUC(BY4743m,"B04") 
  C04<- calc_AUC(BY4743m,"C04") 
  D04<- calc_AUC(BY4743m,"D04") 
  E04<- calc_AUC(BY4743m,"E04") 
  F04<- calc_AUC(BY4743m,"F04") 
  G04<- calc_AUC(BY4743m,"G04") 
  H04<- calc_AUC(BY4743m,"H04") 
  
  A05<- calc_AUC(BY4743m,"A05") 
  B05<- calc_AUC(BY4743m,"B05") 
  C05<- calc_AUC(BY4743m,"C05") 
  D05<- calc_AUC(BY4743m,"D05") 
  E05<- calc_AUC(BY4743m,"E05") 
  F05<- calc_AUC(BY4743m,"F05") 
  G05<- calc_AUC(BY4743m,"G05") 
  H05<- calc_AUC(BY4743m,"H05") 
  
  A06<- calc_AUC(BY4743m,"A06") 
  B06<- calc_AUC(BY4743m,"B06") 
  C06<- calc_AUC(BY4743m,"C06") 
  D06<- calc_AUC(BY4743m,"D06") 
  E06<- calc_AUC(BY4743m,"E06") 
  F06<- calc_AUC(BY4743m,"F06") 
  G06<- calc_AUC(BY4743m,"G06") 
  H06<- calc_AUC(BY4743m,"H06") 
  
  A07<- calc_AUC(BY4743m,"A07") 
  B07<- calc_AUC(BY4743m,"B07") 
  C07<- calc_AUC(BY4743m,"C07") 
  D07<- calc_AUC(BY4743m,"D07") 
  E07<- calc_AUC(BY4743m,"E07") 
  F07<- calc_AUC(BY4743m,"F07") 
  G07<- calc_AUC(BY4743m,"G07") 
  H07<- calc_AUC(BY4743m,"H07")
  
  A08<- calc_AUC(BY4743m,"A08") 
  B08<- calc_AUC(BY4743m,"B08") 
  C08<- calc_AUC(BY4743m,"C08") 
  D08<- calc_AUC(BY4743m,"D08") 
  E08<- calc_AUC(BY4743m,"E08") 
  F08<- calc_AUC(BY4743m,"F08") 
  G08<- calc_AUC(BY4743m,"G08") 
  H08<- calc_AUC(BY4743m,"H08") 
  
  A09<- calc_AUC(BY4743m,"A09") 
  B09<- calc_AUC(BY4743m,"B09") 
  C09<- calc_AUC(BY4743m,"C09") 
  D09<- calc_AUC(BY4743m,"D09") 
  E09<- calc_AUC(BY4743m,"E09")
  F09<- calc_AUC(BY4743m,"F09")
  G09<- calc_AUC(BY4743m,"G09")
  H09<- calc_AUC(BY4743m,"H09")
  
  A10<- calc_AUC(BY4743m,"A10") 
  B10<- calc_AUC(BY4743m,"B10") 
  C10<- calc_AUC(BY4743m,"C10") 
  D10<- calc_AUC(BY4743m,"D10") 
  E10<- calc_AUC(BY4743m,"E10")
  F10<- calc_AUC(BY4743m,"F10")
  G10<- calc_AUC(BY4743m,"G10")
  H10<- calc_AUC(BY4743m,"H10")
  
  A11<- calc_AUC(BY4743m,"A11") 
  B11<- calc_AUC(BY4743m,"A11") 
  B11<- calc_AUC(BY4743m,"B11") 
  C11<- calc_AUC(BY4743m,"C11") 
  D11<- calc_AUC(BY4743m,"D11") 
  E11<- calc_AUC(BY4743m,"E11")
  F11<- calc_AUC(BY4743m,"F11")
  G11<- calc_AUC(BY4743m,"G11")
  H11<- calc_AUC(BY4743m,"H11")
  
  A12<- calc_AUC(BY4743m,"A12") 
  B12<- calc_AUC(BY4743m,"B12") 
  C12<- calc_AUC(BY4743m,"C12") 
  D12<- calc_AUC(BY4743m,"D12") 
  E12<- calc_AUC(BY4743m,"E12")
  F12<- calc_AUC(BY4743m,"F12")
  G12<- calc_AUC(BY4743m,"G12")
  H12<- calc_AUC(BY4743m,"H12")
  
  
  AUC<-tibble(A01,	B01,	C01,	D01,	E01,	F01,	G01,	H01, 
              A02,	B02,	C02,	D02,	E02,	F02,	G02,	H02,
              A03,	B03,	C03,	D03,	E03,	F03,	G03,	H03,
              A04,	B04,	C04,	D04,	E04,	F04,	G04,	H04,
              A05,	B05,	C05,	D05,	E05,	F05,	G05,	H05,
              A06,	B06,	C06,	D06,	E06,	F06,	G06,	H06,
              A07,	B07,	C07,	D07,	E07,	F07,	G07,	H07,
              A08,	B08,	C08,	D08,	E08,	F08,	G08,	H08,
              A09,	B09,	C09,	D09,	E09,	F09,	G09,	H09,
              A10,	B10,	C10,	D10,	E10,	F10,	G10,	H10,
              A11,	B11,	C11,	D11,	E11,	F11,	G11,	H11,
              A12,	B12,	C12,	D12,	E12,	F12,	G12,	H12)
  plate_id<-BY4743m%>%
    select(well, plate)
  
  auc<-melt(AUC)
  names(auc) <- c("well", "auc")
  aucdata <- add_plate(
    data = auc, 
    file = "PLATE MAP.csv",
    well_ids_column = "well")%>%
    merge(plate_id, by = "well")%>%
    unique()
  
}

```

```{r control AUC}
calc_AUC2 <- function(n,z){
  x <- n %>%
    filter(well == z)%>%
    select(runtime)  
  
  X<-x$runtime
  
  
  y <- n %>%
    filter(well == z)%>%
    select(measure_pp) 
  Y<-y$measure_pp 
  
  
  sum(diff(X)*rollmean(Y,2))
}

calc_AUC_plate2 <- function(BY4743m){
  
  A01<- calc_AUC(BY4743m,"A01") 
  B01<- calc_AUC(BY4743m,"B01") 
  C01<- calc_AUC(BY4743m,"C01") 
  D01<- calc_AUC(BY4743m,"D01") 
  E01<- calc_AUC(BY4743m,"E01") 
  F01<- calc_AUC(BY4743m,"F01") 
  G01<- calc_AUC(BY4743m,"G01")  
  H01<- calc_AUC(BY4743m,"H01")  
  
  A02<- calc_AUC(BY4743m,"A02") 
  B02<- calc_AUC(BY4743m,"B02") 
  C02<- calc_AUC(BY4743m,"C02")  
  D02<- calc_AUC(BY4743m,"D02") 
  E02<- calc_AUC(BY4743m,"E02") 
  F02<- calc_AUC(BY4743m,"F02") 
  G02<- calc_AUC(BY4743m,"G02") 
  H02<- calc_AUC(BY4743m,"H02") 
  
  A03<- calc_AUC(BY4743m,"A03") 
  B03<- calc_AUC(BY4743m,"B03") 
  C03<- calc_AUC(BY4743m,"C03") 
  D03<- calc_AUC(BY4743m,"D03") 
  E03<- calc_AUC(BY4743m,"E03") 
  F03<- calc_AUC(BY4743m,"F03") 
  G03<- calc_AUC(BY4743m,"G03") 
  H03<- calc_AUC(BY4743m,"H03") 
  
  A04<- calc_AUC(BY4743m,"A04") 
  B04<- calc_AUC(BY4743m,"B04") 
  C04<- calc_AUC(BY4743m,"C04") 
  D04<- calc_AUC(BY4743m,"D04") 
  E04<- calc_AUC(BY4743m,"E04") 
  F04<- calc_AUC(BY4743m,"F04") 
  G04<- calc_AUC(BY4743m,"G04") 
  H04<- calc_AUC(BY4743m,"H04") 
  
  A05<- calc_AUC(BY4743m,"A05") 
  B05<- calc_AUC(BY4743m,"B05") 
  C05<- calc_AUC(BY4743m,"C05") 
  D05<- calc_AUC(BY4743m,"D05") 
  E05<- calc_AUC(BY4743m,"E05") 
  F05<- calc_AUC(BY4743m,"F05") 
  G05<- calc_AUC(BY4743m,"G05") 
  H05<- calc_AUC(BY4743m,"H05") 
  
  A06<- calc_AUC(BY4743m,"A06") 
  B06<- calc_AUC(BY4743m,"B06") 
  C06<- calc_AUC(BY4743m,"C06") 
  D06<- calc_AUC(BY4743m,"D06") 
  E06<- calc_AUC(BY4743m,"E06") 
  F06<- calc_AUC(BY4743m,"F06") 
  G06<- calc_AUC(BY4743m,"G06") 
  H06<- calc_AUC(BY4743m,"H06") 
  
  A07<- calc_AUC(BY4743m,"A07") 
  B07<- calc_AUC(BY4743m,"B07") 
  C07<- calc_AUC(BY4743m,"C07") 
  D07<- calc_AUC(BY4743m,"D07") 
  E07<- calc_AUC(BY4743m,"E07") 
  F07<- calc_AUC(BY4743m,"F07") 
  G07<- calc_AUC(BY4743m,"G07") 
  H07<- calc_AUC(BY4743m,"H07")
  
  A08<- calc_AUC(BY4743m,"A08") 
  B08<- calc_AUC(BY4743m,"B08") 
  C08<- calc_AUC(BY4743m,"C08") 
  D08<- calc_AUC(BY4743m,"D08") 
  E08<- calc_AUC(BY4743m,"E08") 
  F08<- calc_AUC(BY4743m,"F08") 
  G08<- calc_AUC(BY4743m,"G08") 
  H08<- calc_AUC(BY4743m,"H08") 
  
  A09<- calc_AUC(BY4743m,"A09") 
  B09<- calc_AUC(BY4743m,"B09") 
  C09<- calc_AUC(BY4743m,"C09") 
  D09<- calc_AUC(BY4743m,"D09") 
  E09<- calc_AUC(BY4743m,"E09")
  F09<- calc_AUC(BY4743m,"F09")
  G09<- calc_AUC(BY4743m,"G09")
  H09<- calc_AUC(BY4743m,"H09")
  
  A10<- calc_AUC(BY4743m,"A10") 
  B10<- calc_AUC(BY4743m,"B10") 
  C10<- calc_AUC(BY4743m,"C10") 
  D10<- calc_AUC(BY4743m,"D10") 
  E10<- calc_AUC(BY4743m,"E10")
  F10<- calc_AUC(BY4743m,"F10")
  G10<- calc_AUC(BY4743m,"G10")
  H10<- calc_AUC(BY4743m,"H10")
  
  A11<- calc_AUC(BY4743m,"A11") 
  B11<- calc_AUC(BY4743m,"A11") 
  B11<- calc_AUC(BY4743m,"B11") 
  C11<- calc_AUC(BY4743m,"C11") 
  D11<- calc_AUC(BY4743m,"D11") 
  E11<- calc_AUC(BY4743m,"E11")
  F11<- calc_AUC(BY4743m,"F11")
  G11<- calc_AUC(BY4743m,"G11")
  H11<- calc_AUC(BY4743m,"H11")
  
  A12<- calc_AUC(BY4743m,"A12") 
  B12<- calc_AUC(BY4743m,"B12") 
  C12<- calc_AUC(BY4743m,"C12") 
  D12<- calc_AUC(BY4743m,"D12") 
  E12<- calc_AUC(BY4743m,"E12")
  F12<- calc_AUC(BY4743m,"F12")
  G12<- calc_AUC(BY4743m,"G12")
  H12<- calc_AUC(BY4743m,"H12")
  
  
  AUC<-tibble(A01,	B01,	C01,	D01,	E01,	F01,	G01,	H01, 
              A02,	B02,	C02,	D02,	E02,	F02,	G02,	H02,
              A03,	B03,	C03,	D03,	E03,	F03,	G03,	H03,
              A04,	B04,	C04,	D04,	E04,	F04,	G04,	H04,
              A05,	B05,	C05,	D05,	E05,	F05,	G05,	H05,
              A06,	B06,	C06,	D06,	E06,	F06,	G06,	H06,
              A07,	B07,	C07,	D07,	E07,	F07,	G07,	H07,
              A08,	B08,	C08,	D08,	E08,	F08,	G08,	H08,
              A09,	B09,	C09,	D09,	E09,	F09,	G09,	H09,
              A10,	B10,	C10,	D10,	E10,	F10,	G10,	H10,
              A11,	B11,	C11,	D11,	E11,	F11,	G11,	H11,
              A12,	B12,	C12,	D12,	E12,	F12,	G12,	H12)
  
  auc<-melt(AUC)
  names(auc) <- c("well", "auc")
  aucdata <- add_plate(
    data = auc, 
    file = "m_contol_platemap.csv",
    well_ids_column = "well")
  
}

```

FUNCTION: calculate relative fitness: on plate, off plate, and to by4743
```{r relfit}
## to by4743
#x = byauc data
#y = sample auc measures
rel_fit_to_BY<-  function(y, x){
 
  byauc<- x%>%
   rename_col_by_position(2, byauc)%>%
   select(sample, well, byauc)

 byrel<-y%>%
    merge(byauc, by = c("sample", "well"))%>%
    mutate(rel_fit_to_by = auc/byauc)%>%
    select(-byauc)
  
}

##on plate
# x = plate auc
on_plate_rel_fit<- function(x){
  
  rel_scores<-reshape2::dcast(x, well~plate, fun.aggregate = mean, value.var = "auc")%>%
    column_to_rownames(var="well")
  
  on_rel<-x%>% 
    group_by(solvent) %>% 
    bind_rows(., .) %>%
    mutate(rel_fit_on_plate = ifelse(test = (solvent == 'ETOH'), 
                                      yes = auc/rel_scores["C01", 1],
                                      no = ifelse(test = (solvent == 'ETOH-2'), 
                                                  yes = auc/rel_scores["C07", 1],
                                                  no = ifelse(test = (solvent == 'DMSO'),
                                                              yes = auc/rel_scores["B01", 1],
                                                              no = ifelse(test = (solvent =='DMSO-2'),
                                                                          yes = auc/rel_scores["B07", 1],
                                                                          no = ifelse(test = (solvent =='H2O'),
                                                                                      yes= auc/rel_scores["A01", 1],
                                                                                      no =  auc/rel_scores["A07", 1]))))))%>%
    
    unique()
}

## off plate 
#x= table off plate ave summary measures
#y= table sample measures
#z = current sample name in ""
off_plate_rel_fit<- function(x, y, z){
  
  rel_scores<-reshape2::dcast(x, compound~sample, fun.aggregate = mean, value.var = "AVE_auc")%>%
    column_to_rownames(var="compound")
  
  off_rel<-y%>% 
    group_by(solvent) %>% 
    bind_rows(., .) %>%
    mutate(rel_fit_off_plate = ifelse(test = (solvent == 'ETOH'), 
                                      yes = auc/rel_scores["ETOH",z],
                                      no = ifelse(test = (solvent == 'ETOH-2'), 
                                                  yes = auc/rel_scores["ETOH",z],
                                                  no = ifelse(test = (solvent == 'DMSO'),
                                                              yes = auc/rel_scores["DMSO",z],
                                                              no = ifelse(test = (solvent =='DMSO-2'),
                                                                          yes = auc/rel_scores["DMSO",z],
                                                                          no = ifelse(test = (solvent =='H2O'),
                                                                                      yes= auc/rel_scores["H2O",z],
                                                                                      no =  auc/rel_scores["H2O",z]))))))%>%
    
    unique()
  }

##calculate all 
#a = control messures
#b = current sample mesures
#c = "current sample"
#d = BY4743 auc measures
relative_fitness<-function(a,b,c,d){
by_rels<-off_plate_rel_fit(a, b, c)%>%
  on_plate_rel_fit()%>%
  rel_fit_to_BY(d)
}

```

 

FUNCTION: calculate average ofeach metric for each compound
```{r ploy relfit}
plot_rel_fit <- function(X){ 
  X%>% 
    mutate(plate = 1) %>% 
    unnest() %>% 
    mtp_ggplot(aes(plate = plate, well = well)) + 
    mtp_spec_96well() + 
    geom_footprint() + 
    geom_notched_border() +
    geom_col_label() + 
    geom_row_label() + 
    geom_well_rect(aes(fill = control, alpha = rel_fit_on_plate)) + 
    geom_well_line(aes(x = runtime, y = measure)) + 
    geom_well_text(aes(label = sample))
  
}
```

