---
title: "sig_testing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggpubr)
library(viridis)
library(car)
```
#SIG IS COMPARISON OF MU OR MAX GROWTH RATES
## LOOK FOR SIG BETWEEN PLATES AS A WAY OF DETERMING RELATION 

```{r get right data}
plate<-c("S1L1","S2L1",'S2L2',"S3L1","S3L2","S4L1","S4L2")
strain<-c("BY4743","U5.05","S6.14","S6.45","S6.113","W.34.70", "WLP.644")

ps2<-as.data.frame(cbind(plate,strain))

drug2_mu<-d2_sum_metrics%>%
  select( mu, sample, well, plate, control, solvent )%>%
  merge(ps2)%>%
  select(-plate)

half2<-drug2_mu%>%
  select(strain, sample, mu, control)
half2<-half2[half2$control !=1,] %>%
  select(-control)%>%
  rename_col_by_position(3,"d2_mu_2")
drug2_mu2<-drug2_mu[drug2_mu$control !=2,]%>%
  select(-control)%>%
  rename_col_by_position(1, "d2_mu")

d2_mu<-merge(drug2_mu2, half2)

plate<- c("S1L1", "S1L2", "S2L1","S2L2","S3L1","S3L2")
strain<-c("S6.14","S6.45", "S6.113", "U5.05","WLP.644","W.34.70")

ps3<-as.data.frame(cbind(plate,strain))

drug3_mu<-d2_sum_metrics3%>%
  select( mu, sample, well, plate, control, solvent )%>%
  merge(ps3)%>%
  select(-plate)


half2.3<-drug3_mu%>%
  select(strain, sample, mu, control)
half2.3<-half2.3[half2.3$control !=1,] %>%
  select(-control)%>%
  rename_col_by_position(3,"d3_mu_2")
drug3_mu2<-drug3_mu[drug3_mu$control !=2,]%>%
  select(-control)%>%
  rename_col_by_position(1, "d3_mu")

d3_mu<-merge(drug3_mu2, half2.3)

plate<- c("S1L1", "S1L2", "S2L1","S2L2","S3L1","S3L2")
strain<-c("S6.14","S6.45", "S6.113", "U5.05","W.34.70","WLP.644")

ps4<-as.data.frame(cbind(plate,strain))

drug4_mu<-d4_sum_metrics%>%
  select( mu, sample, well,plate, control, solvent )%>%
  merge(ps4)%>%
  select(-plate)


half2.4<-drug4_mu%>%
  select(strain, sample, mu, control)
half2.4<-half2.4[half2.4$control !=1,] %>%
  select(-control)%>%
  rename_col_by_position(3,"d4_mu_2")
drug4_mu2<-drug4_mu[drug4_mu$control !=2,]%>%
  select(-control)%>%
  rename_col_by_position(1, "d4_mu")

d4_mu<-merge(drug4_mu2, half2.4)



samples_max_gr<-merge(d3_mu, d2_mu, drop = F)%>%
  merge(d4_mu, drop = F)

#need to: find mean and SD 
#split by strain and solvent and arrange by control 
```

```{r mean and sd}

max_gr<-samples_max_gr%>%
  select(-well)%>%
  split(samples_max_gr$strain, drop = F)

S113solv<-max_gr$S6.113


s113solv<-split(S113solv, S113solv$solvent, drop = F)

s113dmso<-s113solv$DMSO

S113DMSO<-melt(s113dmso,id.vars = 'sample', measure.vars = c('d2_mu', 'd2_mu_2','d3_mu', 'd3_mu_2'), value.name = "mu", na.rm = T)
 
s113d<-S113DMSO%>%
  mutate_at(vars(sample), funs (factor))
ss<-s113d

ss$sample <- ordered(ss$sample,
                         levels = c("DMSO control", 
                                    "5-Fluorouracil" ,
                                    "6-Azauracil",
                                    "CCCP",
                                    "Cinnamic acid",
                                    "Cycloheximide", 
                                    "EDTA",
                                    "Fluconazole",
                                    "Guanidine hydrochloride",
                                    "Miconazole Nitrate",     
                                    "Miltefosine",
                                    "Nystatin " ,
                                    "Triclosan"   ))


sg<-group_by(s113h2o, sample) %>%
  summarise(
    count = n(),
    mean = mean(mu, na.rm = TRUE),
    sd = sd(mu, na.rm = TRUE)
  )

#####
s113h2o<-s113solv$H2O

s113h2o<-melt(s113h2o,id.vars = 'sample', measure.vars = c('d2_mu', 'd2_mu_2','d3_mu', 'd3_mu_2',"d4_mu", "d4_mu_2"), value.name = "mu", na.rm = T)%>%
  mutate_at(vars(sample), funs (factor))


s113h2o$sample <- ordered(s113h2o$sample,
                         levels = c( "H2O control ", 
                                    "2-Deoxy-D-glucose" , "3-Amino-1,2,4- triazole" , "4-Aminopyridine" ,"5-Fluorocytosine" , "Azaserine*",
                                    "Benzamidine" , "Blasticidin hydrochloride" ,"Caffeine", "Cetylpyridinium chloride",
                                    "Chlorpromazine hydrochloride ", "Compound 48/80*" , "Copper(II) sulfate", "Dequalinium Chloride" , 
                                    "Diamide", "DTT", "Hydroxyurea" , "Hygromycin B" , "methylmethane sulfonate", "Pentamidine Isethionate",
                                    "Poly-L-lysine hydrochloride" ,  "Sodium Fluoride" ,"Sodium metasilicate" , "Sodium Orthovanadate" ,
                                    "Sodium Selenate","Tamoxifen","Tartaric acid" ,"Thialysine","Thiourea" ,"Trifluoperazine" ,
                                    "Urea hydrogen peroxide"))
                         
     levels(s113h2o$sample)
####
     
s113ETOH<-s113solv$ETOH

s113ETOH<-melt(s113ETOH,id.vars = 'sample', measure.vars = c('d2_mu', 'd2_mu_2','d3_mu', 'd3_mu_2'), value.name = "mu", na.rm = T)%>%
  mutate_at(vars(sample), funs (factor))


s113ETOH$sample <- ordered(s113ETOH$sample,
                         levels = c( "ETOH control ", 
                                    "Menadione ",
                                    "Myclobutanil",
                                    "Propiconazole"))
                         
     levels(s113ETOH$sample)                 
                        
```



```{r plots}
ggboxplot(s113ETOH, x = "sample", y = "mu", 
          color = "sample", palette = viridis(31),
          order = c(  "ETOH control ", 
                                    "Menadione ",
                                    "Myclobutanil",
                                    "Propiconazole"),
          ylab = "mu", xlab = "Treatment")

ggline(ss, x = "sample", y = "mu", 
       add = c("mean_se", "jitter"), 
        order = c("DMSO control", 
                                    "5-Fluorouracil" ,
                                    "6-Azauracil",
                                    "CCCP",
                                    "Cinnamic acid",
                                    "Cycloheximide", 
                                    "EDTA",
                                    "Fluconazole",
                                    "Guanidine hydrochloride",
                                    "Miconazole Nitrate",     
                                    "Miltefosine",
                                    "Nystatin " ,
                                    "Triclosan"   ),
       ylab = "mu", xlab = "Treatment")
```

```{r t-test}


vv<-pairwise.t.test(ss$mu, ss$sample,
                 p.adjust.method = "fdr")
bo<-as.data.frame (vv$p.value)  %>%
  rename_col_by_position(1, "p_adj" )%>%
  select("p_adj")%>%
  rownames_to_column( var = "sample")
  






########


vvh<-pairwise.t.test(s113h2o$mu, s113h2o$sample,
                 p.adjust.method = "fdr")
boh<-as.data.frame (vvh$p.value)  %>%
  rename_col_by_position(1, "p_adj" )%>%
  select("p_adj")%>%
  rownames_to_column( var = "sample")
  



##########


vve<-pairwise.t.test(s113ETOH$mu, s113ETOH$sample,
                 p.adjust.method = "fdr")

boe<-as.data.frame (vve$p.value) %>%
  rename_col_by_position(1, "p_adj" )%>%
  select("p_adj")%>%
  rownames_to_column( var = "sample")
  

s113_pvalues<-rbind(boh,boe, bo)

96*2
93*2
```

```{r pvalues}
s14_pv<-get_p_values(max_gr$S6.14)
s45_pv<-get_p_values(max_gr$S6.45)
s113_pv<-get_p_values(max_gr$S6.113)
u5_pv<-get_p_values(max_gr$U5.05)
wlp_pv<-get_p_values(max_gr$WLP.644)
w34_pv<-get_p_values(max_gr$W.34.70)

samples_pvalues<-rbind(s14_pv,s45_pv,s113_pv,u5_pv,wlp_pv, w34_pv)

```


```{r sig if}
samples_p_sig<- samples_pvalues%>%
  mutate(sig = ifelse(test = (p_adj <= .05), 
                      yes = 1,
                      no = 0))
samp_sig<-samples_p_sig%>%
  select(sample, sig)

xtx<-as.data.frame(table(samp_sig))

hhhh<-xtx%>%
  mutate(f_sig = ifelse(test = (Freq == 6),
                        yes = 1,
                        no =  0))%>%
  select(-Freq)
hhhh$f_sig[hhhh$f_sig == 0]<-NA
sig_drug<-na.omit(hhhh)

sig_drugs<-sig_drug%>%
  mutate(significance = ifelse(test = (sig == 0),
                        yes = "Never",
                        no =  "Always"))%>%
  select(-sig, -f_sig)
write.csv(sig_drugs, "C:/Users/SamBr/documents/yeast/RF2/sig_drugs_d2-4.csv")
write.csv(samples_p_sig, "C:/Users/SamBr/documents/yeast/RF2/sample_p_value_d2-4.csv")
```


```{r plot}
 samples_p_sig2<- merge(  samples_p_sig, ps3)
d2_sum_measures3x<- merge(  d2_sum_measures3, ps3)


meas_pvalues_3<- left_join(d2_sum_measures3x, samples_p_sig2, by = c("plate", "sample", "strain"), drop = F)%>%
  mutate_all(~replace(., is.na(.), 0))

#on_plate_sig_plots<-
  meas_pvalues_3%>% 
    unnest() %>% 
    mtp_ggplot(aes(plate = plate, well = well)) + 
    mtp_spec_96well() + 
    geom_footprint()+ 
    geom_notched_border() +
    geom_col_label(size = 2) + 
    geom_row_label(size = 2) + 
    geom_well_rect(aes(fill = control, alpha = sig)) + 
    geom_well_line(aes(x = runtime, y = measure)) + 
    geom_well_text(aes(label = sample )) + 
    facet_wrap(~plate, ncol = 1) 



```



```{r plot}
 samples_p_sig_off2<- merge(  samples_p_sig_off, ps3)
d2_sum_measures3x<- merge(  d2_sum_measures3, ps3)


meas_pvalues_off_3<- left_join(d2_sum_measures3x, samples_p_sig_off2, by = c("plate", "sample", "strain"), drop = F)%>%
  mutate_all(~replace(., is.na(.), 0))

#on_plate_sig_plots<-
  meas_pvalues_3%>% 
    unnest() %>% 
    mtp_ggplot(aes(plate = plate, well = well)) + 
    mtp_spec_96well() + 
    geom_footprint()+ 
    geom_notched_border() +
    geom_col_label(size = 2) + 
    geom_row_label(size = 2) + 
    geom_well_rect(aes(fill = control, alpha = sig)) + 
    geom_well_line(aes(x = runtime, y = measure)) + 
    geom_well_text(aes(label = sample )) + 
    facet_wrap(~plate, ncol = 1) 


?facet_wrap
```


```{r mean sd }

s14_msd<-get_mean_SD(max_gr$S6.14)
s45_msd<-get_mean_SD(max_gr$S6.45)
s113_msd<-get_mean_SD(max_gr$S6.113)
u5_msd<-get_mean_SD(max_gr$U5.05)
wlp_msd<-get_mean_SD(max_gr$WLP.644)
w34_msd<-get_mean_SD(max_gr$W.34.70)


samples_mean_sd<- rbind(s14_msd,s45_msd,s113_msd,u5_msd, wlp_msd,w34_msd)
write.csv(samples_mean_sd, "C:/Users/SamBr/documents/yeast/RF2/samples_mean_sd_d2-4.csv")


```